/**
 ******************************************************************************
 * @file      sysmem.c
 * @author    Generated by STM32CubeMX
 * @brief     System Memory calls file
 *
 *            For more information about which C functions
 *            need which of these lowlevel functions
 *            please consult the Newlib or Picolibc libc manual
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/* Includes */
#include <errno.h>
#include <stdint.h>
#include <stddef.h>

/**
 * Pointer to the current high watermark of the heap usage
 */
static uint8_t *__sbrk_heap_end = NULL;

/* Boundaries can be supplied by a native regression test without pretending
   that linker-defined absolute symbols are ordinary host variables. */
#ifndef SBRK_HEAP_START
extern uint8_t _end; /* Symbol defined in the linker script */
#define SBRK_HEAP_START ((uintptr_t)&_end)
#endif
#ifndef SBRK_HEAP_LIMIT
extern uint8_t _estack; /* Symbol defined in the linker script */
extern uint32_t _Min_Stack_Size; /* Absolute symbol defined in the linker script */
#define SBRK_HEAP_LIMIT ((uintptr_t)&_estack - (uintptr_t)&_Min_Stack_Size)
#endif

/**
 * @brief _sbrk() allocates memory to the newlib heap and is used by malloc
 *        and others from the C library
 *
 * @verbatim
 * ############################################################################
 * #  .data  #  .bss  #       newlib heap       #          MSP stack          #
 * #         #        #                         # Reserved by _Min_Stack_Size #
 * ############################################################################
 * ^-- RAM start      ^-- _end                             _estack, RAM end --^
 * @endverbatim
 *
 * This implementation starts allocating at the '_end' linker symbol
 * The '_Min_Stack_Size' linker symbol reserves a memory for the MSP stack
 * The implementation considers '_estack' linker symbol to be RAM end
 * NOTE: If the MSP stack, at any point during execution, grows larger than the
 * reserved size, please increase the '_Min_Stack_Size'.
 *
 * @param incr Memory size
 * @return Pointer to allocated memory
 */
void *_sbrk(ptrdiff_t incr)
{
  const uintptr_t heap_start = SBRK_HEAP_START;
  const uintptr_t heap_limit = SBRK_HEAP_LIMIT;

  /* Initialize heap end at first call */
  if (NULL == __sbrk_heap_end)
  {
    __sbrk_heap_end = (uint8_t *)heap_start;
  }

  uintptr_t current = (uintptr_t)__sbrk_heap_end;
  if (current < heap_start || current > heap_limit) {
    errno = ENOMEM;
    return (void *)-1;
  }
  uintptr_t next;
  if (incr >= 0) {
    uintptr_t growth = (uintptr_t)incr;
    if (growth > heap_limit - current) { errno = ENOMEM; return (void *)-1; }
    next = current + growth;
  } else {
    /* -(incr + 1) avoids signed overflow for PTRDIFF_MIN. */
    uintptr_t shrink = (uintptr_t)(-(incr + 1)) + 1U;
    if (shrink > current - heap_start) { errno = ENOMEM; return (void *)-1; }
    next = current - shrink;
  }
  __sbrk_heap_end = (uint8_t *)next;
  return (void *)current;
}

#if defined(__PICOLIBC__)
  // Picolibc expects syscalls without the leading underscore.
  // This creates a strong alias so that
  // calls to `sbrk()` are resolved to our `_sbrk()` implementation.
  __strong_reference(_sbrk, sbrk);
#endif
